
name: CI

on:
  push:
    branches: ["develop"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # - uses: taiki-e/install-action@cargo-llvm-cov
      #   continue-on-error: true
      # - run: mkdir build
      #   working-directory: ./web
      # - run: ./tools/update-coverage-badge.ps1
      #   shell: pwsh
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: update codecov in readme